FROM node:lts as build
WORKDIR /signalrchat.frontend
COPY . .
RUN npm ci
RUN npm run build

FROM nginx:alpine
RUN apk upgrade --update-cache --available && apk add openssl
WORKDIR /signalrchat.frontend
RUN mkdir -p /usr/share/nginx/certificate
COPY SignalRChat.pfx /usr/share/nginx/certificate/. 
WORKDIR /usr/share/nginx/certificate
RUN openssl pkcs12 -in SignalRChat.pfx -clcerts -nokeys -out domain.crt -password pass:AakhzdF7cgXL8f
RUN openssl pkcs12 -in SignalRChat.pfx -nocerts -nodes -out domain.rsa -password pass:AakhzdF7cgXL8f

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /signalrchat.frontend/build .

WORKDIR /signalrchat.frontend
COPY nginx.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]